# Post Physicians
POST http://localhost:9090/patient-management/physicians
content-type: application/json

[{
    "id": "physician00001",
    "name": "John Smith",
    "specialization": "Peadiatrics"
},
{
    "id": "physician00002",
    "name": "Jane Carter",
    "specialization": "Internal Medicine"
},
{
    "id": "physician00003",
    "name": "Kyle Schmidt",
    "specialization": "Family Medicine"
}]


# Post Manufacturers
POST http://localhost:9090/patient-management/manufacturers
content-type: application/json

[{
    "id": "manufacturer00001",
    "name": "Pfizer",
    "countryOfOrigin": "USA"
},
{
    "id": "manufacturer00002",
    "name": "AstraZeneca",
    "countryOfOrigin": "UK"
}]



# Post Drugs
POST http://localhost:9090/patient-management/drugs
content-type: application/json

[{
    "id": "drug00001",
    "name": "Norvasc",
    "description": "treat for hypertension",
    "manufacturerId": "manufacturer00001"
},
{
    "id": "drug00002",
    "name": "INDERAL",
    "manufacturerId": "manufacturer00002",
    "description": "treat for hypertension"
},
{
    "id": "drug00003",
    "name": "NEXIUM",
    "manufacturerId": "manufacturer00002",
    "description": "treat for indigestion"
}]

# Post Patients
POST http://localhost:9090/patient-management/patients
content-type: application/json

[{
    "id": "patient00001", 
    "name": "Jane Doe", 
    "age": 37
},
{
    "id": "patient00002", 
    "name": "John Doe", 
    "age": 30
},
{
    "id": "patient00003", 
    "name": "Jacob Doe", 
    "age": 7
}]

# Drug Assignments
POST http://localhost:9090/patient-management/drug_assignments
content-type: application/json

[{
    "drugId": "drug0001", 
    "patientId": "patient00001", 
    "physicianId": "physician00001", 
    "id": "000001", 
    "quantity": 100
},
{
    "drugId": "drug0002", 
    "patientId": "patient00002", 
    "physicianId": "physician00002", 
    "id": "000002", 
    "quantity": 100
},
{
    "drugId": "drug0003", 
    "patientId": "patient00003", 
    "physicianId": "physician00003", 
    "id": "000003", 
    "quantity": 100
}]


# Post Patient Assignments
POST http://localhost:9090/patient-management/patient_assignments
content-type: application/json

[{
    "patientId": "patient00001", 
    "physicianId": "physician00001", 
    "id": "assignment000001"
},
{
    "patientId": "patient00002", 
    "physicianId": "physician00002", 
    "id": "assignment000002"
},
{
    "patientId": "patient00003", 
    "physicianId": "physician00003", 
    "id": "assignment000003"
}]


# Post Blood Pressure
POST http://localhost:9090/patient-management/blood_pressure
content-type: application/json

[{
    "patientId": "patient00001", 
    "systolic": 150, 
    "diastolic": 98, 
    "id": "patient00001", 
    "timestamp": "2023:07:02:17:30:00"
},
{
    "patientId": "patient00001", 
    "systolic": 155, 
    "diastolic": 95, 
    "id": "patient00001", 
    "timestamp": "2023:07:02:19:30:00"
},
{
    "patientId": "patient00001", 
    "systolic": 155, 
    "diastolic": 95, 
    "id": "patient00001", 
    "timestamp": "2023:07:02:21:30:00"
},
{
    "patientId": "patient00001", 
    "systolic": 155, 
    "diastolic": 95, 
    "id": "patient00001", 
    "timestamp": "2023:07:02:23:30:00"
},
{
    "patientId": "patient00002", 
    "systolic": 145, 
    "diastolic": 90, 
    "id": "patient00002", 
    "timestamp": "2023:07:02:17:30:00"
},
{
    "patientId": "patient00002", 
    "systolic": 146, 
    "diastolic": 85, 
    "id": "patient00002", 
    "timestamp": "2023:07:02:19:30:00"
},
{
    "patientId": "patient00002", 
    "systolic": 143, 
    "diastolic": 85, 
    "id": "patient00002", 
    "timestamp": "2023:07:02:21:30:00"
},
{
    "patientId": "patient00002", 
    "systolic": 1140, 
    "diastolic": 85, 
    "id": "patient00002", 
    "timestamp": "2023:07:02:23:30:00"
},
{
    "patientId": "patient00003", 
    "systolic": 110, 
    "diastolic": 70, 
    "id": "patient00003", 
    "timestamp": "2023:07:02:17:30:00"
},
{
    "patientId": "patient00003", 
    "systolic": 112, 
    "diastolic": 75, 
    "id": "patient00003", 
    "timestamp": "2023:07:02:19:30:00"
},
{
    "patientId": "patient00003", 
    "systolic": 114, 
    "diastolic": 75, 
    "id": "patient00003", 
    "timestamp": "2023:07:02:21:30:00"
},
{
    "patientId": "patient00003", 
    "systolic": 116, 
    "diastolic": 75, 
    "id": "patient00003", 
    "timestamp": "2023:07:02:23:30:00"
}]

# Get PhysicianLogs
GET http://localhost:9090/patient-management/physicians

# Get PatientLogs 
GET http://localhost:9090/patient-management/patients/patient00003

# Update Blood Pressure
PUT http://localhost:9090/patient-management/bloodpressure/patient00003/2023%3A07%3A02%3A21%3A30%3A00
content-type: application/json

{
    "systolic": 118,
    "diastolic": 75
}
 